theme: cids-theme
pagination:
  pagerSize: 18
enableRobotsTXT: true
removePathAccents: true
ignoreLogs: ['warning-goldmark-raw-html']
params:
  plausible: cids.ch
  debug:
    productionUrl: https://cids.ch