theme: cids-theme
_merge: deep
pagination:
  pagerSize: 18
enableRobotsTXT: true
removePathAccents: true
ignoreLogs: ['warning-goldmark-raw-html']
params:
  plausible: cids.ch
  debug:
    productionUrl: https://cids.ch
  projects:
    single:
      meta:
        position: hero
        options:
          reading_time: false
          share: false
          with_labels: false